version: '3.9'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - proxy-conf:/etc/nginx/conf.d
      - proxy-vhost:/etc/nginx/vhost.d
      - proxy-html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs

  letsencrypt:
    image: nginxproxy/acme-companion:latest
    container_name: nginx-letsencrypt
    restart: always
    environment:
      - DEFAULT_EMAIL=you@example.com
    volumes:
      - proxy-conf:/etc/nginx/conf.d
      - proxy-vhost:/etc/nginx/vhost.d
      - proxy-html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs

  frontend:
    image: suq-alfalah-frontend:latest
    environment:
      - VIRTUAL_HOST=your-domain.com
      - LETSENCRYPT_HOST=your-domain.com
      - LETSENCRYPT_EMAIL=you@example.com
    depends_on:
      - backend

  backend:
    image: suq-alfalah-backend:latest
    environment:
      - VIRTUAL_HOST=api.your-domain.com
      - LETSENCRYPT_HOST=api.your-domain.com
      - LETSENCRYPT_EMAIL=you@example.com
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}

volumes:
  proxy-conf:
  proxy-vhost:
  proxy-html:
  certs:
